// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: processor.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProcessingStatus with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProcessingStatus) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProcessingStatus with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProcessingStatusMultiError, or nil if none found.
func (m *ProcessingStatus) ValidateAll() error {
	return m.validate(true)
}

func (m *ProcessingStatus) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsRunning

	if all {
		switch v := interface{}(m.GetLastRun()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProcessingStatusValidationError{
					field:  "LastRun",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProcessingStatusValidationError{
					field:  "LastRun",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastRun()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProcessingStatusValidationError{
				field:  "LastRun",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetNextRun()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProcessingStatusValidationError{
					field:  "NextRun",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProcessingStatusValidationError{
					field:  "NextRun",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNextRun()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProcessingStatusValidationError{
				field:  "NextRun",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ProcessingStatusMultiError(errors)
	}

	return nil
}

// ProcessingStatusMultiError is an error wrapping multiple validation errors
// returned by ProcessingStatus.ValidateAll() if the designated constraints
// aren't met.
type ProcessingStatusMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProcessingStatusMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProcessingStatusMultiError) AllErrors() []error { return m }

// ProcessingStatusValidationError is the validation error returned by
// ProcessingStatus.Validate if the designated constraints aren't met.
type ProcessingStatusValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProcessingStatusValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProcessingStatusValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProcessingStatusValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProcessingStatusValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProcessingStatusValidationError) ErrorName() string { return "ProcessingStatusValidationError" }

// Error satisfies the builtin error interface
func (e ProcessingStatusValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProcessingStatus.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProcessingStatusValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProcessingStatusValidationError{}
